# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "77.77.77.7"
  config.vm.hostname = "farmahead-dev"
  config.vm.provision :shell, path: "./bootstrap.sh"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../", "/vagrant_files"

  config.vm.provider "virtualbox" do |vb|  
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

#  config.vm.provision "ansible" do |ansible|
#    # ansible.verbose = "v"
#    ansible.playbook = "../ansible/vagrant_playbook.yml"
#    ansible.inventory_path = "../ansible/hosts/vagrant_hosts.ini"
#    ansible.config_file = "../ansible/ansible.cfg"
#    ansible.compatibility_mode = "2.0"
#  end
end