export const MARKETS_RECEIVED = 'MARKETS_RECEIVED';
export const VENDORS_RECEIVED = 'VENDORS_RECEIVED';
export const PRODUCE_RECEIVED = 'PRODUCE_RECEIVED';
export const PAGE_REQUESTED = 'PAGE_REQUESTED';