export const FILTERED_PAGE_REQUESTED = 'FILTERED_PAGE_REQUESTED'
export const FILTERED_MARKETS_RECEIVED = 'FILTERED_MARKETS_RECEIVED'
export const FILTERED_VENDORS_RECEIVED = 'FILTERED_VENDORS_RECEIVED'
